name: quail_57
description: "Ludum Dare 57 App."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0-206.0.dev
  
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  
flutter_launcher_icons:
  android: "launcher_icon"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon.png"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  fonts:
   - family: buggy
     fonts:
      - asset: assets/small.ttf

  assets:
   - assets/